name: Run Foundry Tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install forge dependencies
              run: forge install

            - name: Install npm dependencies
              run: npm i

            - name: Check contract sizes
              run: forge build --sizes

            - name: Check gas snapshots
              run: forge snapshot --check

            - name: Run tests
              run: forge test
